name: Node.js CI/CD Workflow

# Trigger events for both main and backend-dev branches
on:
  push:
    branches:
      - main
      - backend-dev
  pull_request:
    branches:
      - main
      - backend-dev

jobs:
  build-and-test:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm ci
        # npm ci is faster and ensures clean installs for CI environments.

      # Step 4: Lint Code
      - name: Lint Code
        run: npm run lint
        continue-on-error: true
        # Allow lint failures to warn instead of failing CI entirely. Remove if strict.

      # Step 5: Run Tests
      - name: Run Tests
        run: npm test

  deploy:
    name: Deployment Check
    needs: build-and-test # Runs only if build-and-test succeeds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Ensure Build Passes
        run: npm run build
        # Optional: Add deployment steps (if hosting is configured, like AWS or Heroku).
